<a href="https://colab.research.google.com/github/dsalvat/art-of-data-driven-business/blob/main/01_TheArtofDataDrivenBusiness.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print('select elements by index: ', arr[0])
print('slice elements of the array: ',arr[1:5])
print('ending point of the array: ', arr[4:])
print('ending point of the array: ', arr[:4])


select elements by index:  1
slice elements of the array:  [2 3 4 5]
ending point of the array:  [5]
ending point of the array:  [1 2 3 4]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
arr = np.stack((arr1, arr2), axis = 0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
np.mean(arr, axis=1)

array([2., 5.])

In [7]:
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])